// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: apg.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	FuncName      string                 `protobuf:"bytes,3,opt,name=func_name,json=funcName,proto3" json:"func_name,omitempty"`
	ModelVersion  string                 `protobuf:"bytes,4,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	FilePath      string                 `protobuf:"bytes,5,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobRequest) Reset() {
	*x = JobRequest{}
	mi := &file_apg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRequest) ProtoMessage() {}

func (x *JobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRequest.ProtoReflect.Descriptor instead.
func (*JobRequest) Descriptor() ([]byte, []int) {
	return file_apg_proto_rawDescGZIP(), []int{0}
}

func (x *JobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *JobRequest) GetFuncName() string {
	if x != nil {
		return x.FuncName
	}
	return ""
}

func (x *JobRequest) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *JobRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type Attempt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candidate     string                 `protobuf:"bytes,1,opt,name=candidate,proto3" json:"candidate,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	Gate          string                 `protobuf:"bytes,3,opt,name=gate,proto3" json:"gate,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attempt) Reset() {
	*x = Attempt{}
	mi := &file_apg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attempt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attempt) ProtoMessage() {}

func (x *Attempt) ProtoReflect() protoreflect.Message {
	mi := &file_apg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attempt.ProtoReflect.Descriptor instead.
func (*Attempt) Descriptor() ([]byte, []int) {
	return file_apg_proto_rawDescGZIP(), []int{1}
}

func (x *Attempt) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

func (x *Attempt) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Attempt) GetGate() string {
	if x != nil {
		return x.Gate
	}
	return ""
}

func (x *Attempt) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type JobResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success         bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Score           float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	BestCandidate   string                 `protobuf:"bytes,4,opt,name=best_candidate,json=bestCandidate,proto3" json:"best_candidate,omitempty"`
	AnnotatedIrJson string                 `protobuf:"bytes,5,opt,name=annotated_ir_json,json=annotatedIrJson,proto3" json:"annotated_ir_json,omitempty"`
	Rounds          int32                  `protobuf:"varint,6,opt,name=rounds,proto3" json:"rounds,omitempty"`
	Error           string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	Attempts        []*Attempt             `protobuf:"bytes,8,rep,name=attempts,proto3" json:"attempts,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *JobResponse) Reset() {
	*x = JobResponse{}
	mi := &file_apg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResponse) ProtoMessage() {}

func (x *JobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResponse.ProtoReflect.Descriptor instead.
func (*JobResponse) Descriptor() ([]byte, []int) {
	return file_apg_proto_rawDescGZIP(), []int{2}
}

func (x *JobResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JobResponse) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *JobResponse) GetBestCandidate() string {
	if x != nil {
		return x.BestCandidate
	}
	return ""
}

func (x *JobResponse) GetAnnotatedIrJson() string {
	if x != nil {
		return x.AnnotatedIrJson
	}
	return ""
}

func (x *JobResponse) GetRounds() int32 {
	if x != nil {
		return x.Rounds
	}
	return 0
}

func (x *JobResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *JobResponse) GetAttempts() []*Attempt {
	if x != nil {
		return x.Attempts
	}
	return nil
}

var File_apg_proto protoreflect.FileDescriptor

const file_apg_proto_rawDesc = "" +
	"\n" +
	"\tapg.proto\x12\x03apg\"\x93\x01\n" +
	"\n" +
	"JobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x1b\n" +
	"\tfunc_name\x18\x03 \x01(\tR\bfuncName\x12#\n" +
	"\rmodel_version\x18\x04 \x01(\tR\fmodelVersion\x12\x1b\n" +
	"\tfile_path\x18\x05 \x01(\tR\bfilePath\"g\n" +
	"\aAttempt\x12\x1c\n" +
	"\tcandidate\x18\x01 \x01(\tR\tcandidate\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\x12\n" +
	"\x04gate\x18\x03 \x01(\tR\x04gate\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xf8\x01\n" +
	"\vJobResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\x12%\n" +
	"\x0ebest_candidate\x18\x04 \x01(\tR\rbestCandidate\x12*\n" +
	"\x11annotated_ir_json\x18\x05 \x01(\tR\x0fannotatedIrJson\x12\x16\n" +
	"\x06rounds\x18\x06 \x01(\x05R\x06rounds\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x12(\n" +
	"\battempts\x18\b \x03(\v2\f.apg.AttemptR\battemptsB\x14Z\x12apg/internal/protob\x06proto3"

var (
	file_apg_proto_rawDescOnce sync.Once
	file_apg_proto_rawDescData []byte
)

func file_apg_proto_rawDescGZIP() []byte {
	file_apg_proto_rawDescOnce.Do(func() {
		file_apg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apg_proto_rawDesc), len(file_apg_proto_rawDesc)))
	})
	return file_apg_proto_rawDescData
}

var file_apg_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_apg_proto_goTypes = []any{
	(*JobRequest)(nil),  // 0: apg.JobRequest
	(*Attempt)(nil),     // 1: apg.Attempt
	(*JobResponse)(nil), // 2: apg.JobResponse
}
var file_apg_proto_depIdxs = []int32{
	1, // 0: apg.JobResponse.attempts:type_name -> apg.Attempt
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_apg_proto_init() }
func file_apg_proto_init() {
	if File_apg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apg_proto_rawDesc), len(file_apg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apg_proto_goTypes,
		DependencyIndexes: file_apg_proto_depIdxs,
		MessageInfos:      file_apg_proto_msgTypes,
	}.Build()
	File_apg_proto = out.File
	file_apg_proto_goTypes = nil
	file_apg_proto_depIdxs = nil
}
