# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: apg.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'apg.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapg.proto\x12\x03\x61pg\"R\n\nJobRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x11\n\tfunc_name\x18\x03 \x01(\t\x12\x15\n\rmodel_version\x18\x04 \x01(\t\"\x8b\x01\n\x0bJobResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\r\n\x05score\x18\x03 \x01(\x01\x12\x16\n\x0e\x62\x65st_candidate\x18\x04 \x01(\t\x12\x19\n\x11\x61nnotated_ir_json\x18\x05 \x01(\t\x12\x0e\n\x06rounds\x18\x06 \x01(\x05\x12\r\n\x05\x65rror\x18\x07 \x01(\tB\x14Z\x12\x61pg/internal/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apg_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\022apg/internal/proto'
  _globals['_JOBREQUEST']._serialized_start=18
  _globals['_JOBREQUEST']._serialized_end=100
  _globals['_JOBRESPONSE']._serialized_start=103
  _globals['_JOBRESPONSE']._serialized_end=242
# @@protoc_insertion_point(module_scope)
